### PR TITLE
Fixes and improvements to SinkWriter Example2

### PR DESCRIPTION
**Pull request by rmesch**
Fixed runtime error on selecting multiple bitmaps. Speedup of bitmap resizing using D2D1_1
Reduced memory usage by using only one frame buffer Eliminated need for saving corrected bitmaps to file.

### CODE REVIEW

**Comment by FactoryXCode** [comment]
Hi, Thank you for this contribution.
Supported versions are XE2 and above. To make exceptions for example versions < XE2 like the NativeInt should be implemented in WinApi.WinApiTypes and defined in WinApiTypes.inc. Both units are designed to support various Delphi versions. 

Regards, Tony.

**Review by FactoryXCode — APPROVED** [review]
Thank you Renate,
I will merge this into the master.

Tony.

**Comment by rmesch** [comment]
Thanks for the merge. This was my first pull request, so I'm sorry if I didn't get everything right. Thanks for fixing it.
Renate

**Comment by FactoryXCode** [comment]
Y're welcome.
I had to edit / remove some unused code in the sample, no problem.
Regards Tony.

**Pull request merged**
