### PR TITLE
Update MfPlayerClassX.pas

### PR DESCRIPTION
**Pull request by adaloveless**
fix access violation on shutdown of Mfplayer X

### CODE REVIEW

**Review by FactoryXCode — COMMENTED** [review]
Releasing those interfaces is done @ procedure TMfPlayerX.BeforeDestruction();  that calls procedure TMfPlayerX.Clear() , where all interfaces are being released.
So, what's the difference?

It seems this is a random issue.  Since session is a-sync.
After the command 'Stop' before closing the process should be handled before continuing dereferencing the interfaces. 
I think, the best possible method to handle this, is in method function TMfPlayerX.UpdatePendingCommands(req: TRequest): HRESULT;
I Added the following code lines at the end of this method:

```
 // Handle messages in queue.              // <
 HandleMessages(GetCurrentThread()); // < Add this codeline here.

 UpdateCaption();
 Result := hr;
```

Also:
function TMFCallBack.Invoke(pAsyncResult: IMFAsyncResult): HResult;
```
try
  if not Assigned(MFPresentationClock) then
    begin
      hr := MF_E_NO_CLOCK;
      Exit;
    end;

  if not Assigned(MfTimer) then // < Add this codeline here.
    Exit;                                         //
```

I tested this and it look likes those solutions solved the random issue.

Regards, Tony.

**Comment by adaloveless** [comment]
Tony, thanks for looking into this.  It was definitely a race-condition of sorts.  My original suggestion was based upon a different, older branch, so I went back and "played with it some more"  

I was seeing issues during application.terminate() as well as when I'd click the "open" button while a video was already playing.

After moving to the latest branch and playing around with it some more...mMy temporary solution was to use a TTimer event with a 1ms delay to put some time between the shutdown() operation and the subsequent reopening.  I tried moving them to messages with PostMessage() but even that wasn't enough... a timer was required.  I'll try your suggestion and see how that works out for me. 

Thanks for the response... and your contributions.  I will try and become a more active contributor going forward.  Currently I have some Media-Foundation code in C++ that could definitely be "more elegant".  And my contributions, if possible, will be to attempt to meet some my special requirements....  which will include cross-fading videos and the ability to synchronize Video via UDP across a network... some stuff I have kinda-sorta-basically working in C++.

I'll try to become a more active contributor.  Thanks again.

**Comment by adaloveless** [comment]
Tony, I tried out your suggestion, and it seemed to do the trick!  I don't have to put use a timer between closing and reopening, nor shutting down.

**Comment by FactoryXCode** [comment]
Ok found another issue: function TMFCallBack.Invoke(pAsyncResult: IMFAsyncResult): HResult;

The timer is being called while it's nil. See edited first comment.
I did commit the whole sample with all changes. 

Any contributor is welcome.
And many thanks for your contribution on this issue.

Regards, Tony.

**Pull request closed without merging**
